### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1388]
Looking at the [milestone](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/milestone/16), it's about time we release version 1.0.0 (understatement intended).

Proposed target release date: **Monday July 2nd**.

I also think that it may be a good idea to do more regular (smaller) releases.

There are a couple of open issues/PRs which I'd like to see finished/merged before then:
- [x] PRs ~~#1374~~, ~~#1384~~, ~~#1386~~, ~~#1387~~ are IMO all good to go & ready to merge
- [ ] PR #1378 (previously #1233) still needs a little work, but not much. Would be great if @moorscode has some time this week to finish it off. I'll do a final review once the build passes.
    If @moorscode does not have time this week, this sniff can be moved to the 1.1.0 release.
- [x] PR #1366 - I need to do a last review & hope all is good. If so, I'll merge it ASAP ;-) /cc @grappler
    Update: review done, minor changes requested. 
- [ ] PR #1364 - If I remember correctly, that one still needs a little work on the token walking. Would be great if @grappler has some time this week to finish it off.
    If not, this sniff can be moved to the 1.1.0 release.
- [ ] PR #1349 and #1351 need a secondary review on the functions listed vs WP core. Any takers ? /cc @johnbillion 
- [ ] PR #1265 has an unresolved discussion. @JDGrimes What are your thoughts on this at this time ?
- [x] Issue #1368 - ~~I will open a PR for this shortly~~ PR #1390 addresses this.
- [ ] Issues #1218, #1272 (PHPCS 3.2.x annotations) - I'm still stuck on one last bit, but will take a decision on this soon and pull the PR fixing the issues I've found (I'm not guaranteeing completeness, but the PR should cover most cases).
    Update: PR #1407 takes care of the majority of this. Second PR upcoming.
- [ ] Issue #1254 is currently unresolved. It would be good to take a decision about this and if it would be decided to go ahead, implement this for the 1.0.0 version to prevent people having to rename the same sniff twice in rulesets/inline annotations. /cc @JDGrimes 
- [x] Create changelog for the 1.0.0 release - ~~volunteers welcome, if needs be, I can probably do this myself sometime this week~~ I'm working on this.

Opinions ? Additions ?

/cc @WordPress-Coding-Standards/wpcs-admins

**Comment by jrfnl** [comment]
- [ ] Issue #1309 will need a PR before `1.0.0` can be released as well.

**Comment by JDGrimes** [comment]
> PR #1265 has an unresolved discussion. @JDGrimes What are your thoughts on this at this time ?

I think that more research needs to be done before a decision can be made on it. I will not have time to look into it in before 1.0.0 is released. I suggest punting, unless somebody else wants to take it over, or there is a minimal approach.

> Issue #1254 is currently unresolved. It would be good to take a decision about this and if it would be decided to go ahead, implement this for the 1.0.0 version to prevent people having to rename the same sniff twice in rulesets/inline annotations. /cc @JDGrimes

Nobody has expressed a strong opinion on it, so maybe it isn't worth the change. It really depends on how the sniff might evolve in the future (whether a second sniff will be introduced or this one will be changed to have the option to just catch low-hanging fruit), and I cannot predict/commit to that.

**Comment by jrfnl** [comment]
FYI: I'll get back to this on Thursday. Only a few more things left to do before we're ready to release.

**Comment by jrfnl** [comment]
### Status update:

The release will close end of the week.

* I'm keeping my fingers crossed (with confidence!) that #1366 (deprecated param values), #1378 (enqueued resources parameters) and #1410 (deprecated VIP ruleset) will all make it to the finish line before the end of the week, so they can be shipped in the `1.0.0` release :tada: 

    Thank you @moorscode, @grappler and @tomjn for working with us to get this done in time!

* As there has been no traction on #1364 (capabilities check), that PR will move to the next release.

* It would be great if someone would still volunteer to do the secondary review for #1349 and #1351.

* Most of the work for #1218, #1272 (PHPCS 3.2.x annotations) has been pulled and merged. I'm still working on the last sniff which needs fixing for this (`ArrayIndentation`). This really is not an easy one to solve, I've only been struggling with it for six months now :sunglasses:
    Anyway, I feel that it's getting somewhere, so hoping against hope I'll be able to finish it before the release.

* As per @JDGrimes' reply above, I've moved #1265 out of the `1.0.0` milestone and #1254 will not be addressed in this release either.

* The changelog for the release is ready and I'm updating it when PRs are merged. Once the last PRs for the milestone are complete, I will pull the PR for this.

**Comment by jrfnl** [comment]
### Status update:

All relevant open issues have been resolved, all PRs which were still needed for the 1.0.0 release have been merged.

Some things - like the fix for PHPCS annotations for the `ArrayIndentation` sniff - have not made it into the release, so these will move to a future release.

Providing I get at least one more approval for the release PR #1392, I will release WPCS 1.0.0 tomorrow (Wednesday July 25th UTC).

**Comment by jrfnl** [comment]
And... the release is out: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/1.0.0

**Comment by jrfnl** [comment]
Release tweet: https://twitter.com/jrf_nl/status/1022186349355585536

**Comment by GaryJones** [comment]
Well done everyone, particularly @jrfnl :-)
