### ISSUE TITLE
Drop deprecated features in WPCS 2.0.0

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1446]
This has been discussed in other issues already and IIRC there is consensus about this, so this issue is just to document what needs to be done for this.

- [x] Remove sniffs which have been deprecated in WPCS 1.0.0 or earlier.
    This includes:
    - The old sniff base classes from before these were turned into abstract classes.
    - The sniffs which were moved around/renamed in WPCS 1.0.0.
    - The VIP sniffs which are slated for removal.
    - Any unit tests files involving these sniffs.
- [x] Remove all sniff properties which have been deprecated in WPCS 1.0.0 or earlier.
    - This mostly involves sniff properties which have been renamed in previous versions.
    - Unit tests using the old sniff property names should also be removed.
- [x] Remove support for passing array sniff properties as strings. This behaviour was deprecated in WPCS 1.0.0.
    As long as the new minimum supported PHPCS version is PHPCS 3.3.0 or higher, this will not cause a problem for unit tests involving array sniff properties, though these setting of these properties will need to be changed from `propertyname value1,value2,value3` to `propertyname[] value1,value2,value3`
- [x] Update the Wiki to remove references to the old sniff and property names.

Please leave a comment if I seem to be forgetting something in this action list.
